"""empty message

Revision ID: 4b1fc60c0e42
Revises: e0a3bded0a05
Create Date: 2017-09-20 11:19:09.317967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1fc60c0e42'
down_revision = 'e0a3bded0a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('canonical_url', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('videos', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('poster_filename', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('video_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table("videos") as batch_op:
        batch_op.drop_column('video_filename')
        batch_op.drop_column('poster_filename')
        batch_op.drop_column('duration')
        batch_op.drop_column('created_at')
        batch_op.drop_column('canonical_url')
